### ISSUE TITLE
[FEATURE] [k3s] Support for installer script [tracker]

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/kubernetes-formula#23]
### Is your feature request related to a problem?

K3S can be installed by script (I think this was tested successfully during formula development). But K3S script provides no checksum so the `k3s.binary` is the default state in this formula. 

### Describe the solution you'd like

Ths Issue tracks https://github.com/rancher/k3s/issues/2378 - once that issue is fixed K3S script can be delivered here.

### Describe alternatives you've considered

https://github.com/saltstack-formulas/kubernetes-formula#kubernetes-k3s-binary works fine.

**Comment by BadgerOps** [comment]
Looks like this exists!
```
vagrant]# curl -sfL https://get.k3s.io | sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.19.3+k3s3 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.19.3+k3s3/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.19.3+k3s3/k3s
```

**Comment by noelmcloughlin** [comment]
Thanks, @BadgerOps, I never noticed that.
```
$ curl -LO https://github.com/rancher/k3s/releases/download/v1.19.3+k3s3/sha256sum-amd64.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   645  100   645    0     0    645      0  0:00:01 --:--:--  0:00:01  1212
100   245  100   245    0     0    245      0  0:00:01  0:00:01 --:--:--  1570

$ cat sha256sum-amd64.txt
ad296fb03eb31334eb88ba4c54690145d3f343bde17a1331803093c544025b4a  k3s
c6fcc39f41d3b7a1f49f8d6494127348b10afca3f9859525833d1eaebb07d6b5  k3s-airgap-images-amd64.tar
f4cf2933e56bfa43494967d1dad25066a404161f720324d1bee91dcd778a2e40  k3s-images.txt
```

**Comment by BadgerOps** [comment]
https://twitter.com/ibuildthecloud/status/1330979320618094592?s=20 - But https://get.k3s.io/sha256 does exist now. 

I'm hacking on this locally right now and will submit a PR later today or tomorrow if thats cool

**Comment by BadgerOps** [comment]
> Thanks, @BadgerOps, I never noticed that.
> 
> ```
> $ curl -LO https://github.com/rancher/k3s/releases/download/v1.19.3+k3s3/sha256sum-amd64.txt
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   645  100   645    0     0    645      0  0:00:01 --:--:--  0:00:01  1212
> 100   245  100   245    0     0    245      0  0:00:01  0:00:01 --:--:--  1570
> 
> $ cat sha256sum-amd64.txt
> ad296fb03eb31334eb88ba4c54690145d3f343bde17a1331803093c544025b4a  k3s
> c6fcc39f41d3b7a1f49f8d6494127348b10afca3f9859525833d1eaebb07d6b5  k3s-airgap-images-amd64.tar
> f4cf2933e56bfa43494967d1dad25066a404161f720324d1bee91dcd778a2e40  k3s-images.txt
> ```

in retrospect, I got excited too quickly, this is just for the binary, not validating the script itself, but as per my post above, the whole script now has the requested endpoint, so we're good to go

**Comment by noelmcloughlin** [comment]
Is the endpoint hash sum of the script? If yes, thats good.

**Comment by BadgerOps** [comment]
Sweet, preliminary output:
```
[INFO    ] Running state [/tmp/kubernetes-tmp//k3s-bootstrap.sh] at time 21:56:43.093716
[INFO    ] Executing state file.managed for [/tmp/kubernetes-tmp//k3s-bootstrap.sh]
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'saltmaster', u'tcp://192.168.50.4:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'saltmaster', u'tcp://192.168.50.4:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://192.168.50.4:4506
[DEBUG   ] Trying to connect to: tcp://192.168.50.4:4506
[DEBUG   ] Requesting URL https://get.k3s.io/sha256 using GET method
[DEBUG   ] Using backend: tornado
[DEBUG   ] file.extract_hash: Extracting any supported hash for file matching either of the following: /tmp/kubernetes-tmp//k3s-bootstrap.sh, https://get.k3s.io/vv1.18.10+k3s1/k3s-linux-
[DEBUG   ] file.extract_hash: Line 'd5bdb06c385673e932de17c0cef3c8f5c48bc2143ad06fbaa58ccce4d7766811' contains sha256 hash 'd5bdb06c385673e932de17c0cef3c8f5c48bc2143ad06fbaa58ccce4d7766811', but line did not meet the search criteria
[DEBUG   ] file.extract_hash: Returning the partially identified sha256 hash 'd5bdb06c385673e932de17c0cef3c8f5c48bc2143ad06fbaa58ccce4d7766811'
[DEBUG   ] Requesting URL https://get.k3s.io/vv1.18.10+k3s1/k3s-linux- using GET method
[DEBUG   ] Using backend: tornado
[INFO    ] File changed:
New file
[INFO    ] Completed state [/tmp/kubernetes-tmp//k3s-bootstrap.sh] at time 21:56:43.545494 (duration_in_ms=451.777)

```
Then, manual verification:
```
sha256sum /tmp/kubernetes-tmp/k3s-bootstrap.sh 
d5bdb06c385673e932de17c0cef3c8f5c48bc2143ad06fbaa58ccce4d7766811  /tmp/kubernetes-tmp/k3s-bootstrap.sh
```
And ez-mode diff:
```
diff --git a/kubernetes/map.jinja b/kubernetes/map.jinja
index 43435aa..54e5010 100644
--- a/kubernetes/map.jinja
+++ b/kubernetes/map.jinja
@@ -95,7 +95,7 @@
                 {%- if 'source_hash' in p.script and p.script.source_hash %}
                     {%- do p.script.update({'source_hash': p.script.source_hash}) %}
                 {%- else %}
-                    {%- do p.script.update({'source_hash': url ~ '.sha256'}) %}
+                    {%- do p.script.update({'source_hash': '%s/%s'|format(p.uri_s, 'sha256') }) %}
                 {%- endif %}
             {%- endif %}
         {%- endif %}
```
~Note: I'm testing on Centos7 - the os_family block for  Redhat prevents script from running:~
```
diff --git a/kubernetes/k3s/script/install.sls b/kubernetes/k3s/script/install.sls
index 9946ce5..88e94db 100644
--- a/kubernetes/k3s/script/install.sls
+++ b/kubernetes/k3s/script/install.sls
@@ -7,7 +7,7 @@
 
 {%- if d.k3s.pkg.use_upstream == 'script' %}
 
-    {%- if grains.os_family not in ('RedHat', 'Windows') %}
+    {%- if grains.os_family not in ('Windows') %}
```
~I think we can do maybe just the `os` grain?~

EDIT: I had another error that I attributed to this block and was a bit confused, disregard!

**Comment by noelmcloughlin** [comment]
Yes, `os` grains works for CentOS.  But `os_family` covers CentOS, Amazon, RHEL, fedora.

**Comment by BadgerOps** [comment]
~Yeah, this formula works (so far!) in Centos7, fails in Rhel7 and I'm testing Amazon, Fedora, Suse to see what succeeds/fails on those.~

Edit: disregard, I had some confusion as stated above.

**Comment by BadgerOps** [comment]
Ok, I was confused above on the whole os grains thing, so disregard that - took me a while to get kitchen working on my workstation, with the script install we don't get the same installed folder structure:
```
  ×  kubernetes archive: should be installed (2 failed)
     ×  File /usr/local/k8s-k3s-v1.18.10+k3s1/bin/k3s is expected to exist
     expected File /usr/local/k8s-k3s-v1.18.10+k3s1/bin/k3s to exist
     ✔  File /usr/local/k8s-k3s-v1.18.10+k3s1/bin/k3s is expected not to be directory
     ×  File /usr/local/k8s-k3s-v1.18.10+k3s1/bin/k3s type is expected to eq :file
     
     expected: :file
          got: nil
     
     (compared using ==)

     ✔  File /usr/local/bin/k3s is expected to be file
     ✔  File /usr/local/bin/k3s is expected not to be directory
```
But otherwise it works! 

I'm not that familiar with TK, so I'm not sure if the 'right' solution is an if/else block to check to see if it was installed via script or via binary download, or if there is another way. I'd like to learn the 'correct' way of doing this though! I'm reading through https://www.saltstack.com/blog/testing-your-salt-states-with-kitchen-salt/ tonight to see if I can get a better idea of how to proceed, but if you have a good direction to point me, feel free to do so! :) Cheers
